version: 2

regex: &regex .*

attach_workspace: &attach_workspace
  attach_workspace:
    at: '~/project'

persist_to_workspace: &persist_to_workspace
  persist_to_workspace:
    root: '~'
    paths:
      'project'

defaults: &defaults
  working_directory: '~/project'
  docker: [{image: 'circleci/node:12.19-browsers'}]

workflows:
  version: 2

  pr_pipeline:
    jobs:
      - install_dependencies:
          filters:
            branches:
              ignore: master
      - unit_tests:
          requires: [install_dependencies]
      - lint:
          requires: [install_dependencies]
  merge_pipeline:
    jobs:
      - install_dependencies:
            filters:
              tags:
                only: /.*/
              branches:
                ignore: /.*/
      - unit_tests:
          requires: [install_dependencies]
      - lint:
          requires: [install_dependencies]
      - publish_lib:
          requires: [unit_tests, lint]


jobs:
  install_dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys: ['v1-npm-deps-{{ checksum "~/project/packages/my-proj/package-lock.json"}}', 'v1-npm-deps']
      - run:
          command: |
            cd ~/project/packages/my-proj
            npm install
      - save_cache:
          key: 'v1-npm-deps-{{ checksum "~/project/packages/my-proj/package-lock.json"}}'
          paths: ['~/project/packages/my-proj/node_modules']
      - *persist_to_workspace

  unit_tests:
    <<: *defaults
    steps:
      - *attach_workspace
      - restore_cache:
          keys: ['v1-npm-deps-{{ checksum "project/packages/my-proj/package-lock.json"}}']
      - run:
          command: |
            cd project/packages/my-proj
            npm test

  lint:
    <<: *defaults
    steps:
      - *attach_workspace
      - restore_cache:
          keys: ['v1-npm-deps-{{ checksum "project/packages/my-proj/package-lock.json"}}']
      - run:
          command: |
            ls
            cd project/packages/my-proj
            npm run lint

  publish_lib:
    <<: *defaults
    environment:
      NPM_REGISTRY: https://registry.npmjs.org/
      NPM_USER: wgiger6
      NPM_EMAIL: brextrodesign@gmail.com
    steps:
      - *attach_workspace
      - restore_cache:
          keys: ['v1-npm-deps-{{ checksum "project/packages/my-proj/package-lock.json"}}']
      - run: |
          cd project/packages/my-proj
          npm i npm-cli-adduser
          npx npm-cli-adduser -u $NPM_USER $NPM_EMAIL -p $PASS -r $NPM_REGISTRY
          npm version $CIRCLE_TAG
          npm publish --registry $NPM_REGISTRY



