version: 2

attach_workspace: &attach_workspace
  attach_workspace:
    at: '~/project'

persist_to_workspace: &persist_to_workspace
  persist_to_workspace:
    root: '~/project'

docker_node: &docker_node
  docker: [{image: 'circleci/node:10'}]

workflows:
  version: 2

  merge_pipeline:
    jobs:
      - install_dependencies
      - unit_tests:
          requires: [install_dependencies]
      - lint:
          requires: [install_dependencies]
      - publish:
          requires: [ lint, unit_tests]


jobs:
  install_dependencies:
    <<: *docker_node
    working_directory: ~project/packages/my-proj
    steps:
      - checkout:
          path: ~project/
      - restore_cache:
          keys: ['v1-npm-deps-{{ checksum "packages/my-proj/package-lock.json"}}', 'v1-npm-deps']
      - run:
          command: |
            cd packages/my-proj
            ls
            npm install
      - save_cache:
          key: 'v1-npm-deps-{{ checksum "packages/my-proj/package-lock.json"}}'
          paths: ['node_modules']
      - *persist_to_workspace

  unit_tests:
    <<: *docker_node
    work
    steps:
      - checkout
      - *attach_workspace
      - run: |
          npm test

  lint:
    <<: *docker_node
    steps:
      - checkout
      - *attach_workspace
      - run: |
          npm run lint


  publish:
    <<: *docker_node
    steps:
      - checkout
      - *attach_workspace
      - run: |
          npm publish



