version: 2

attach_workspace: &attach_workspace
  attach_workspace:
    at: '~/project/packages/my-proj'

persist_to_workspace: &persist_to_workspace
  persist_to_workspace:
    root: '~/project/packages/my-proj'

docker_node: &docker_node
  docker: [{image: 'halplatform/hal-build-environments:node10.10-debian9'}]

workflows:
  version: 2

  merge_pipeline:
    jobs:
      - install_dependencies
      - unit_tests:
          requires: [install_dependencies]
      - lint:
          requires: [install_dependencies]
      - publish:
          requires: [ lint, unit_tests]


jobs:
  install_dependencies:
    <<: *docker_node
    steps:
      - restore_cache:
          keys: ['v1-npm-deps-{{ checksum "package-lock.json"}}', 'v1-npm-deps']
      - run: |
          cd packages
          ls
          npm install

      - save_cache:
          key: 'v1-npm-deps-{{ checksum "package-lock.json"}}'
          paths: ['node_modules']
      - *persist_to_workspace

  unit_tests:
    <<: *docker_node
    steps:
      - *attach_workspace
      - run: |
          npm test

  lint:
    <<: *docker_node
    steps:
      - *attach_workspace
      - run: |
          npm run lint


  publish:
    <<: *docker_node
    steps:
      - *attach_workspace
      - run: |
          npm publish



