version: 2

attach_workspace: &attach_workspace
  attach_workspace:
    at: '~/project'

persist_to_workspace: &persist_to_workspace
  persist_to_workspace:
    root: '~'
    paths:
      'project'

defaults: &defaults
  working_directory: '~/project'
  docker: [{image: 'circleci/node:12.19-browsers'}]

workflows:
  version: 2

  merge_pipeline:
    jobs:
      - install_dependencies
      - unit_tests:
          requires: [install_dependencies]
      - lint:
          requires: [install_dependencies]
      - publish:
          requires: [ lint, unit_tests]

jobs:
  install_dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys: ['v1-npm-deps-{{ checksum "~/project/packages/my-proj/package-lock.json"}}', 'v1-npm-deps']
      - run:
          command: |
            cd ~/project/packages/my-proj
            npm install
      - save_cache:
          key: 'v1-npm-deps-{{ checksum "~/project/packages/my-proj/package-lock.json"}}'
          paths: ['node_modules']
      - *persist_to_workspace

  unit_tests:
    <<: *defaults
    steps:
      - *attach_workspace
      - run: ls
      - restore_cache:
          keys: ['v1-npm-deps-{{ checksum "~/project/packages/my-proj/package-lock.json"}}']
      - run:
          command: |
            cd ~/project/packages/my-proj
            npm test

  lint:
    <<: *defaults
    working_directory: ./packages/my-proj
    steps:
      - *attach_workspace
      - restore_cache:
          keys: ['v1-npm-deps-{{ checksum "~/project/packages/my-proj/package-lock.json"}}']
      - run:
          command: |
            ls
            cd ~/project/packages/my-proj
            npm run lint

  # publish_lib:
  #   <<: *defaults
  #   - restore_cache:
  #         keys: ['v1-npm-deps-{{ checksum "~/project/packages/my-proj/package-lock.json"}}']
  #   steps:
  #     - *attach_workspace
  #     - run: |
  #         cd ~/project/packages/my-proj
  #         npm publish



